name: API Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Run tests with Maven
      run: mvn clean test
      
    - name: Upload test reports
      uses: actions/upload-artifact@v4
      if: always()  # Run even if previous steps failed
      with:
        name: test-reports
        path: target/surefire-reports/
        retention-days: 7
